spring.application.name=spring

#Adres bazy danych
spring.datasource.url=jdbc:postgresql://localhost:5432/moja_baza

#dane logowania
spring.datasource.username=postgres
spring.datasource.password=1234

# update - zazwyczaj / create -reset bazy
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
